### ISSUE TITLE
Add access_token_ttl param option to README

### ISSUE THREAD

**Issue by mikeabiezzi** [grokify/ringcentral-sdk-ruby#2]
The README doesn't mention this, but I figured out via reading through the code that I can pass a custom param access_token_ttl=x to `Client#authorize_code(code, access_token_ttl: 600)` to set a custom ttl. It would be helpful to point this out in the README for other developers.

**Comment by grokify** [comment]
@mjezzi Good investigation and idea for updating the docs. PR is welcome.

**Comment by grokify** [comment]
Updated master branch to support this for `Client#authorize_password` and `Cient#authorize_user` as well.

**Comment by grokify** [comment]
Resolved in [release 1.3.0](https://github.com/grokify/ringcentral-sdk-ruby/releases/tag/1.3.0).
1. Updated `Client#authorize_password` and `Cient#authorize_user` to accept OAuth params
2. Updated doc to mention params
