### ISSUE TITLE
Deprecated farady dependencies

### ISSUE THREAD

**Issue by mnort9** [grokify/ringcentral-sdk-ruby#76]
This library depends on pre-1.0 faraday and faraday middleware libraries that are deprecated. This is causing dependency conflicts with other libraries that are depending on newer versions of faraday.

**Comment by grokify** [comment]
Thanks for posting this.

Update is in progress on `master` branch.

**Comment by grokify** [comment]
Updated in `v2.3.0`:

* https://rubygems.org/gems/ringcentral_sdk/versions/2.3.0
* https://github.com/grokify/ringcentral-sdk-ruby/releases/tag/v2.3.0

Version 3 can also be used, but it has a few minor breaking changes described here:

https://github.com/grokify/ringcentral-sdk-ruby/releases/tag/v3.0.0
